# Site specific settings
title: "DEF CON 11396"
name: "DEF CON 11396"
keywords: "DEF CON GROUP, Rome"
description: "DEF CON group @ Rome, Italy"

baseurl: ""
#cover: "/assets/img/cover.svg"

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong

twitter: defcon11396
#facebook: 
github: defcon11396
#google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
